import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Dancing_Script } from "next/font/google";

const dancing = Dancing_Script({ subsets: ["latin"], weight: ["400", "700"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-black ${dancing.className}`}
      >
        {children}
      </body>
    </html>
  );
}
